title: "Ihmisen käyttöjärjestelmä"
description: "Henkilökohtainen blogi tekoälystä, systeemiajattelusta, resilienssistä, kirjoittamisesta ja arjen käyttöjärjestelmistä."
url: "https://kataguru.github.io"
baseurl: "/blogi"
lang: "fi"
timezone: "Europe/Helsinki"
markdown: kramdown
permalink: /:year/:month/:day/:title/

# GoatCounter-kävijälaskuri.
# Luo GoatCounteriin sivusto koodilla "kataguru" tai vaihda tähän oma sivustokoodi.
# GoatCounterin asetuksista pitää sallia laskurin näyttäminen sivustolla.
goatcounter_code: "kataguru"

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
